apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  description: This task will clone repo into workspace.
  workspaces:
    - name: source
  params:
    - name: repo-url
      description: Repo URL
      type: string
      default: " "
    - name: branch
      description: Branch to be cloned
      type: string
      default: "master"
  steps:
    - name: clone
      image: bitnami/git
      workingDir: $(workspaces.source.path)
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      command: ["git"]
      args: ["clone", "--branch", $(params.branch), $(params.repo-url)]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  description: This task will run quality checks for the code.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to flake8
      type: string
      default: "--count"
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      script: |
        #!/bin/bash
        cd ci-cd-final-project
        export PATH="$PATH:$HOME/.local/bin"
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        flake8 service $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: This task will run unit tests.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      script: |
        #!/bin/bash
        cd ci-cd-final-project
        export PATH="$PATH:$HOME/.local/bin"
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  description: Using as a trigger for build config in openshift
  workspaces:
    - name: source
  params:
    - name: build-config-name
      description: Name for build config
  steps:
    - name: trigger-build-config
      image: quay.io/openshift/origin-cli:4.15
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      script: |
        #!/bin/sh
        oc start-build $(params.build-config-name) --from-dir=ci-cd-final-project/ --follow
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  description: Deploy image to openshift
  params:
    - name: build-image
      description: Image name
    - name: app-name
      description: Deployment name
  steps:
    - name: deploy-image
      image: quay.io/openshift/origin-cli:4.15
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      script: |
        #!/bin/sh
        oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -